language: elixir
elixir:
  - 1.1.1
  - 1.2.0
otp_release:
  - 17.5
  - 18.2.1
sudo: false # to use faster container based build environment
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - h.bing612@gmail.com
